In [1]:
import pandas as pd
import numpy as np

# This notebook merges tender and country data

In [2]:
# import cleaned data
tender_data = pd.read_csv('../data/cleaned_recoded_tender_data.csv')
tender_data.head()

,Unnamed: 0,id,year,title,cpv,contract_type,description,country,buyer_name,buyer_address,buyer_town,contracting_authority_type,contracting_authority_activity,government_procurement_agreement,is_framework_agreement,is_dynamic,is_open,value_eur,saas
0,0,1-2021,2020,cyber threat intelligence infrastructure – des...,['72000000'],Services,enisa seeks to contract service providers for ...,Greece,European Union Agency for Cybersecurity,1 Vasilissis Sofias Street,Maroussi,Other,Other,No,Yes,No,Yes,3150000.0,No
1,1,1000-2015,2014,ds-rempart.,['72910000'],Services,maîtrise d'oeuvre du secours informatique de l...,France,Ministère de l'économie,Secrétariat général – SEP 1a – 18 avenue Léon ...,Paris Cedex 20,Ministry or any other national or federal auth...,General public services,Yes,No,No,Yes,2205140.0,No
2,2,100000-2015,2015,"service de téléphonie filaire, de télécommunic...","['64210000', '64212000', '64221000', '72400000']",Services,"services de téléphonie filaire, de télécommuni...",France,Communauté d'agglomération du Bassin d'Arcacho...,"2 allée d'Espagne, BP 147",Arcachon Cedex,Regional or local authority,Environment,Yes,Yes,No,Yes,NaN,No
3,3,100004-2015,2015,NaN,"['48810000', '48000000']",Services,les prestations objet de la consultation conce...,France,Cerema,Bât. 4 — 25 avenue François Mitterrand — CS 92...,Bron Cedex,Body governed by public law,Environment,Yes,No,No,Yes,450000.0,No
4,4,100004-2018,2018,framework agreement for microsoft licences.,['48000000'],Supplies,"sund, øygarden og fjell kommune hereby invites...",Norway,Sund kommune,Sund Senter,Skogsvåg,Regional or local authority,General public services,Yes,Yes,No,Yes,1227646.6,No

In [6]:
country_data = pd.read_csv('../data/country_data_all_new.csv')

country_data.head()

,country,year,buss_gerd,dii_high,dii_low,dii_very_high,dii_very_low,gdp,gov_gerd,gov_personnel,...,ict_value_added,population,venture,inno_procurement,geo,position_economy,position_efficiency,position_market,pct_employment_gov,pct_gov_procurement
0,Austria,2014,2.20,NaN,NaN,NaN,NaN,36130.0,0.14,NaN,...,4.30,8507786.0,0.008,Good performer,West,5.260071,3.600044,1.052333,16.78,25.23
1,Austria,2015,2.18,24.1,45.1,3.0,27.9,36140.0,0.14,0.1529,...,1.77,8584926.0,0.008,Good performer,West,5.260071,3.600044,1.052333,16.94,25.87
2,Austria,2016,2.19,19.7,46.0,1.8,32.6,36390.0,0.22,NaN,...,2.61,8700471.0,NaN,Good performer,West,5.260071,3.600044,1.052333,16.96,26.40
3,Austria,2017,2.14,22.0,36.7,3.7,37.6,36980.0,0.22,0.2317,...,0.43,8772865.0,NaN,Good performer,West,6.870432,6.361617,1.840410,16.88,26.89
4,Austria,2018,2.16,8.2,37.2,0.7,53.9,37690.0,0.22,NaN,...,1.29,8822267.0,NaN,Good performer,West,6.870432,6.361617,1.840410,16.75,27.10

In [8]:
# Merge the two dataframes
# Merge on country and year
# From country_data keep column called value, but rename it to the name of the indicator

df = tender_data.merge(country_data, how='left', left_on=['country', 'year'], right_on=['country', 'year'])
df = df.drop(df.columns[0], axis=1)
df.head()

,id,year,title,cpv,contract_type,description,country,buyer_name,buyer_address,buyer_town,...,ict_value_added,population,venture,inno_procurement,geo,position_economy,position_efficiency,position_market,pct_employment_gov,pct_gov_procurement
0,1-2021,2020,cyber threat intelligence infrastructure – des...,['72000000'],Services,enisa seeks to contract service providers for ...,Greece,European Union Agency for Cybersecurity,1 Vasilissis Sofias Street,Maroussi,...,42.61,10718565.0,NaN,Modest performer,South,18.909153,5.104497,1.636967,NaN,18.73
1,1000-2015,2014,ds-rempart.,['72910000'],Services,maîtrise d'oeuvre du secours informatique de l...,France,Ministère de l'économie,Secrétariat général – SEP 1a – 18 avenue Léon ...,Paris Cedex 20,...,-0.28,66165980.0,0.035,Moderate performer,West,4.819529,2.095217,0.004815,22.15,26.04
2,100000-2015,2015,"service de téléphonie filaire, de télécommunic...","['64210000', '64212000', '64221000', '72400000']",Services,"services de téléphonie filaire, de télécommuni...",France,Communauté d'agglomération du Bassin d'Arcacho...,"2 allée d'Espagne, BP 147",Arcachon Cedex,...,1.36,66458153.0,0.034,Moderate performer,West,4.819529,2.095217,0.004815,22.17,25.59
3,100004-2015,2015,NaN,"['48810000', '48000000']",Services,les prestations objet de la consultation conce...,France,Cerema,Bât. 4 — 25 avenue François Mitterrand — CS 92...,Bron Cedex,...,1.36,66458153.0,0.034,Moderate performer,West,4.819529,2.095217,0.004815,22.17,25.59
4,100004-2018,2018,framework agreement for microsoft licences.,['48000000'],Supplies,"sund, øygarden og fjell kommune hereby invites...",Norway,Sund kommune,Sund Senter,Skogsvåg,...,-1.50,5295619.0,NaN,Good performer,North,12.905278,2.646988,2.979692,30.69,30.36

In [9]:
df.columns

Index(['id', 'year', 'title', 'cpv', 'contract_type', 'description', 'country',
       'buyer_name', 'buyer_address', 'buyer_town',
       'contracting_authority_type', 'contracting_authority_activity',
       'government_procurement_agreement', 'is_framework_agreement',
       'is_dynamic', 'is_open', 'value_eur', 'saas', 'buss_gerd', 'dii_high',
       'dii_low', 'dii_very_high', 'dii_very_low', 'gdp', 'gov_gerd',
       'gov_personnel', 'ict_employment', 'ict_percent', 'ict_value_added',
       'population', 'venture', 'inno_procurement', 'geo', 'position_economy',
       'position_efficiency', 'position_market', 'pct_employment_gov',
       'pct_gov_procurement'],
      dtype='object')

In [10]:
#shape of df_analysis

df.shape

(295019, 38)

In [11]:
# missing data in population column

df['population'].isnull().sum()

0

In [12]:
df.to_csv('../data/cleaned_recoded_tender_country_data.csv', index=False)

# recoding data for multilevel analysis

In [20]:
# if contract_type is serviced contract, then contract_type_id = 1, else 0

df["contract_type"] = df["contract_type"].apply(lambda x: 1 if x == "Services" else 0)

In [133]:
# recode country column to integers

df["country_id"] = df["country"].astype('category')
df["country_id"] = df["country_id"].cat.codes

# recode year column to itnergers

df["year_id"] = df["year"].astype('category')
df["year_id"] = df["year_id"].cat.codes

# if saas is yes, then saas_id = 1, else 0

df["saas"] = df["saas"].apply(lambda x: 1 if x == "Yes" else 0)

In [139]:
df["country_id"].value_counts(dropna=False)

9     42051
22    40659
10    40418
27    29404
5     16980
30    15734
19    14377
28    13228
21    11304
14     9420
8      9044
1      8727
16     7226
24     7074
12     5983
25     5750
6      5513
13     5447
26     4845
2      4717
23     3945
29     3934
0      3746
3      3689
7      3354
11     3179
15     3083
17     1349
4       755
18      747
20      613
Name: country_id, dtype: int64

In [136]:
df["year_id"].value_counts(dropna=False)

8    57702
7    54152
6    49252
5    45008
1    27702
0    27538
2    27374
4    21572
3    15995
Name: year_id, dtype: int64

# saving data

In [137]:
df.head()

,id,title,cpv,contract_type,description,country,contracting_authority_type,contracting_authority_activity,government_procurement_agreement,currency,...,is_framework_agreement,is_dynamic,is_open,saas,gdp_value,pop_value,contract_type_id,country_id,year_id,saas_id
0,10001-2022,elektrosaimniecības dispečerpunktu un apakšsta...,['72265000'],Services,elektrosaimniecības dispečerpunktu un apakšsta...,latvia,NaN,Urban railway tramway trolleybus or bus services,Yes,EUR,...,NaN,NaN,Yes,No,13200.0,1875757.0,1,15,8,0
1,10003-2022,cs-02 dezvoltare gis la nivelul noului sistem...,['51612000'],Services,servicii de „dezvoltare gis la nivelul noului ...,romania,NaN,Water,No,RON,...,NaN,NaN,Yes,No,10110.0,19038098.0,1,24,8,0
2,10004-2022,platforma esb – enterprise service bus,['72260000'],Services,achizitia ce are ca obiect platforma esb – ent...,romania,NaN,Production transport and distribution of gas a...,Yes,RON,...,NaN,NaN,Yes,No,10110.0,19038098.0,1,24,8,0
3,10006-2022,oficina de gobierno y analitica de datos,['72212461'],Services,oficina de gobierno y analitica de datos,spain,NaN,Airportrelated activities,No,EUR,...,NaN,NaN,Yes,No,24590.0,47432805.0,1,27,8,0
4,10017-2022,"contratación, para la empresa municipal de tra...",['66172000'],Services,"contratación, para la empresa municipal de tra...",spain,NaN,Urban railway tramway trolleybus or bus services,No,EUR,...,NaN,NaN,Yes,No,24590.0,47432805.0,1,27,8,0

In [138]:
# save df to csv
df.to_csv('../data/cleaned_recoded_tender_data_analysis.csv', index=False)